# Generated by Django 3.2.3 on 2021-08-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_id', models.CharField(max_length=10)),
                ('Admin_pass', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
