# Generated by Django 3.2.3 on 2021-08-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_App',
            fields=[
                ('app_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('patient_id', models.PositiveIntegerField(max_length=10)),
                ('doc_id', models.PositiveIntegerField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='Admin_id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
