# Generated by Django 3.2.3 on 2021-08-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210815_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Admin_id',
            new_name='admin_id',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='Admin_pass',
            new_name='admin_pass',
        ),
    ]
