# Generated by Django 3.2.3 on 2021-08-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210815_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_app',
            name='app_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book_app',
            name='doc_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='book_app',
            name='patient_id',
            field=models.PositiveIntegerField(),
        ),
    ]
